motd=Minecraft Server
server-port=25565
difficulty=normal
gamemode=survival
online-mode=true
white-list=true
enforce-whitelist=true
max-players=20
view-distance=10
simulation-distance=8
spawn-protection=0
enable-command-block=true
allow-flight=false
pvp=true
enable-rcon=false
sync-chunk-writes=false
